#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
#   On the 9th iteration, displays "Hi" before "Best School".
cont=0
while [ $cont -lt 10 ];
do
    if [ $cont -eq 9 ]
    then
echo "Hi"
    fi
    echo "Best School"
    let cont=cont+1
done