#!/usr/bin/env bash
#   "bad luck" - the 4th iteration
#   "good luck" - the 8th iteration
#   "Best School" - all other iterations

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
