#!/usr/bin/env bash
#  Script bash displays the content for current directory
#   Only displays the part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done